name: action-publish

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Send dingding notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          secret: ${{ secrets.DING_TALK_SECRET }} # if secret set, action will call API with sign
          body: |
            {
                "msgtype": "markdown",
                "markdown": {
                    "title": '🎉 DingTalk 发布 ${{ github.ref }} 🎉',
                    "text": '21212'
                },
                "at": {
                    "isAtAll": true
                }
            }